FROM golang:1.17 as builder

# Build Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

ENV APP_HOME=/foss/src/app
WORKDIR $APP_HOME

ADD app $APP_HOME
COPY resources $APP_HOME/resources
COPY go.mod /foss/src

#RUN go get github.com/go-delve/delve/cmd/dlv
RUN go build -gcflags "all=-N -l" -o $APP_HOME

# deployment image
FROM scratch

# copy ca-certificates from builder
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

# Final stage
FROM debian:buster
EXPOSE 8083 2345

WORKDIR /apps/
COPY --from=builder /go/bin/dlv /apps/
COPY --from=builder /foss/src/app/ /apps/
CMD ["/apps/dlv", "--listen=:2345", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/apps/app"]